// Built-in theme definitions
import type {Theme} from '../types/theme.types.ts';

export const BUILTIN_THEMES: Record<string, Theme> = {
	dark: {
		name: 'Dark',
		colors: {
			primary: 'blueBright',
            secondary: 'black',
            highlight: 'blackBright',
            background: 'whiteBright',
            text: 'gray',
            accent: 'cyan',
            dim: 'white',
            error: 'red',
            success: 'green',
            warning: 'yellow',
		},
		inverse: false,
	},
	light: {
		name: 'Light',
        colors: {
            primary: 'yellowBright',
            secondary: 'white',
            highlight: 'whiteBright',
            background: 'black',
            text: 'gray',
            accent: 'yellow',
            dim: 'blackBright',
            error: 'red',
            success: 'green',
            warning: 'yellow',
        },
        inverse: false,
    },
	midnight: {
		name: 'Midnight',
		colors: {
			primary: 'magenta',
			secondary: 'purple',
			highlight: 'purple',
			background: 'black',
			text: 'white',
			accent: 'cyan',
			dim: 'gray',
			error: 'red',
			success: 'greenBright',
			warning: 'yellowBright',
		},
		inverse: false,
	},
	matrix: {
		name: 'Matrix',
		colors: {
			primary: 'green',
			secondary: 'greenBright',
			highlight: 'green',
			background: 'black',
			text: 'white',
			accent: 'greenBright',
			dim: 'green',
			error: 'red',
			success: 'greenBright',
			warning: 'yellow',
		},
		inverse: false,
	},
	dracula: {
		name: 'Dracula',
		colors: {
			primary: 'magenta',
			secondary: 'cyan',
			highlight: 'magenta',
			background: 'black',
			text: 'white',
			accent: 'yellow',
			dim: 'gray',
			error: 'red',
			success: 'green',
			warning: 'yellow',
		},
		inverse: false,
	},
	nord: {
		name: 'Nord',
		colors: {
			primary: 'blue',
			secondary: 'cyan',
			highlight: 'blue',
			background: 'black',
			text: 'white',
			accent: 'blueBright',
			dim: 'gray',
			error: 'red',
			success: 'greenBright',
			warning: 'yellow',
		},
		inverse: false,
	},
	solarized: {
		name: 'Solarized',
		colors: {
			primary: 'yellow',
			secondary: 'cyan',
			highlight: 'whiteBright',
			background: 'blue',
			text: 'cyanBright',
			accent: 'magenta',
			dim: 'blueBright',
			error: 'red',
			success: 'green',
			warning: 'yellowBright',
		},
		inverse: false,
	},
	catppuccin: {
		name: 'Catppuccin',
		colors: {
			primary: 'magentaBright',
			secondary: 'cyanBright',
			highlight: 'whiteBright',
			background: 'black',
			text: 'white',
			accent: 'redBright',
			dim: 'gray',
			error: 'red',
			success: 'greenBright',
			warning: 'yellow',
		},
		inverse: false,
	},
};

export const DEFAULT_THEME: Theme = BUILTIN_THEMES['dark'] as Theme;
